theme = "Hydrogen" 
show = ["Host","Machine","Kernel","Distribution","OperatingSystem","DesktopEnvironment","WindowManager","Resolution","Backlight","Packages","LocalIP","Terminal","Shell","Processor","Memory","Battery"]
